import { useState, useEffect } from "react";
import axios from "axios";

const PrintReportModal = ({ isOpen, onClose, adminIdToken }) => {
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (isOpen) {
      fetchStats();
    }
  }, [isOpen]);

  const fetchStats = async () => {
    setLoading(true);
    try {
      const apiUrl = import.meta.env.VITE_API_URL;
      console.log("Fetching stats from:", `${apiUrl}/admin/stats`);

      const response = await axios.get(
        `${apiUrl}/admin/stats`,
        {
          headers: {
            Authorization: `Bearer ${adminIdToken}`,
            "Content-Type": "application/json"
          }
        }
      );
      console.log("Stats response:", response.data);
      setStats(response.data);
    } catch (error) {
      console.error("Error fetching stats:", error.response?.data || error.message);
      setStats({ error: true, message: error.response?.data?.error || "Failed to fetch statistics" });
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Gym Management - Monthly Report</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #000;
            padding-bottom: 15px;
          }
          .header h1 {
            margin: 0;
            font-size: 28px;
          }
          .header p {
            margin: 5px 0;
            color: #666;
          }
          .stats-container {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            margin: 30px 0;
          }
          .stat-box {
            border: 2px solid #ddd;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
            background-color: #f9f9f9;
          }
          .stat-box h3 {
            margin: 0 0 10px 0;
            color: #666;
            font-size: 14px;
            text-transform: uppercase;
          }
          .stat-box .number {
            font-size: 36px;
            font-weight: bold;
            color: #007bff;
            margin: 10px 0;
          }
          .stat-box .detail {
            font-size: 12px;
            color: #999;
          }
          .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #999;
            border-top: 1px solid #ddd;
            padding-top: 20px;
          }
          .summary {
            background-color: #e8f4f8;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
          }
          .summary h3 {
            margin-top: 0;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>VM Fitness - Monthly Report</h1>
          <p>Generated on ${new Date().toLocaleDateString()}</p>
          <p>Report Period: ${new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}</p>
        </div>

        <div class="stats-container">
          <div class="stat-box">
            <h3>New Members</h3>
            <div class="number">${stats?.newMembers || 0}</div>
            <div class="detail">Added this month</div>
          </div>
          <div class="stat-box">
            <h3>Renewed Memberships</h3>
            <div class="number">${stats?.renewedMembers || 0}</div>
            <div class="detail">Renewed this month</div>
          </div>
          <div class="stat-box">
            <h3>Expired Subscriptions</h3>
            <div class="number">${stats?.expiredMembers || 0}</div>
            <div class="detail">Expired this month</div>
          </div>
        </div>

        <div class="summary">
          <h3>Summary</h3>
          <p><strong>Total Active Members:</strong> ${stats?.totalActiveMembers || 0}</p>
          <p><strong>Total Orders This Month:</strong> ${stats?.totalOrders || 0}</p>
          <p><strong>Total Revenue:</strong> ₹${(stats?.totalRevenue || 0).toLocaleString('en-IN')}</p>
        </div>

        <div class="footer">
          <p>This is an automated report generated by VM Fitness Management System</p>
          <p>&copy; ${new Date().getFullYear()} VM Fitness. All rights reserved.</p>
        </div>
      </body>
      </html>
    `;
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.print();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl p-8 max-w-2xl w-full mx-4">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl font-bold">Monthly Report</h2>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700 text-2xl"
          >
            ✕
          </button>
        </div>

        {loading ? (
          <div className="text-center py-8">
            <p className="text-gray-600">Loading statistics...</p>
          </div>
        ) : stats && !stats.error ? (
          <>
            <div className="grid grid-cols-3 gap-4 mb-6">
              <div className="bg-blue-50 p-4 rounded-lg text-center">
                <p className="text-gray-600 text-sm">New Members</p>
                <p className="text-3xl font-bold text-blue-600">{stats.newMembers || 0}</p>
                <p className="text-xs text-gray-500">Added this month</p>
              </div>
              <div className="bg-green-50 p-4 rounded-lg text-center">
                <p className="text-gray-600 text-sm">Renewed Memberships</p>
                <p className="text-3xl font-bold text-green-600">{stats.renewedMembers || 0}</p>
                <p className="text-xs text-gray-500">Renewed this month</p>
              </div>
              <div className="bg-red-50 p-4 rounded-lg text-center">
                <p className="text-gray-600 text-sm">Expired Subscriptions</p>
                <p className="text-3xl font-bold text-red-600">{stats.expiredMembers || 0}</p>
                <p className="text-xs text-gray-500">Expired this month</p>
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg mb-6 space-y-2">
              <p className="flex justify-between">
                <span className="font-semibold">Total Active Members:</span>
                <span>{stats.totalActiveMembers || 0}</span>
              </p>
              <p className="flex justify-between">
                <span className="font-semibold">Total Orders This Month:</span>
                <span>{stats.totalOrders || 0}</span>
              </p>
              <p className="flex justify-between">
                <span className="font-semibold">Total Revenue:</span>
                <span>₹{(stats.totalRevenue || 0).toLocaleString('en-IN')}</span>
              </p>
            </div>

            <div className="flex gap-3">
              <button
                onClick={handlePrint}
                className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition font-semibold"
              >
                🖨️ Print Report
              </button>
              <button
                onClick={onClose}
                className="flex-1 px-4 py-2 bg-gray-300 text-gray-800 rounded-lg hover:bg-gray-400 transition font-semibold"
              >
                Close
              </button>
            </div>
          </>
        ) : (
          <div className="text-center py-8">
            <div className="bg-red-50 p-4 rounded-lg border border-red-200">
              <p className="text-red-600 font-semibold">⚠️ Error Loading Statistics</p>
              <p className="text-red-600 text-sm mt-2">{stats?.message || "Failed to load statistics. Please ensure you have data in the system."}</p>
              <p className="text-gray-500 text-xs mt-3">Please refresh and try again, or ensure admin permissions are correct.</p>
            </div>
            <button
              onClick={onClose}
              className="mt-4 px-4 py-2 bg-gray-300 text-gray-800 rounded-lg hover:bg-gray-400 transition font-semibold"
            >
              Close
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default PrintReportModal;
